### ISSUE TITLE
不是为什么啊

### ISSUE THREAD

**Issue by hhhhhge** [ChaosJulien/XiaoYuanKouSuan_Auto#13]
C:\Users\hhhge\AppData\Local\Programs\Python\Python311\python.exe H:\小猿口算auto\main.py 
Traceback (most recent call last):
  File "H:\小猿口算auto\main.py", line 4, in <module>
    import pytesseract
  File "C:\Users\hhhge\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytesseract\__init__.py", line 2, in <module>
    from .pytesseract import ALTONotSupported
  File "C:\Users\hhhge\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytesseract\pytesseract.py", line 42, in <module>
    import pandas as pd
  File "C:\Users\hhhge\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\__init__.py", line 59, in <module>
    from pandas.core.api import (
  File "C:\Users\hhhge\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\api.py", line 1, in <module>
    from pandas._libs import (
  File "C:\Users\hhhge\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\_libs\__init__.py", line 18, in <module>
    from pandas._libs.interval import Interval
  File "interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by asukaminato0721** [comment]
https://stackoverflow.com/a/78650263/13040423

maybe downgrade numpy to version 1.26.4
